name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install pandoc texlive-xetex 
      
    - name: Generating pdfs
      run: make

    - name: Run Clean
      run: make clean
